[dev]
  command = "gatsby develop" # Command to start your dev server
  port = 8001 # Port that the dev server will be accessible on
  targetPort = 8000 # Port of target app server
  publish = "_site" # If you use a _redirect file, provide the path to your static content folder
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address
  framework = "#custom"

# [[redirects]]
#   from = "https://pixelpink.netlify.app/*"
#   to ="https://pixel-pink.de/:splat"

# [[redirects]]
#   from = "https://www.pixel-pink.de/*"
#   to ="https://pixel-pink.de/:splat"

# # This page got deleted 
# [[redirects]]
#   from = "/more.html"
#   to  = "/"
#   status = 410


# # Redirect browsers set to englisch 
# [[redirects]]
#   from = "/"
#   to = "/en/"
#   status = 302
#   conditions = {Language = ["en"]}

# # Redirect browsers set to german 
# [[redirects]]
#   from = "/en/"
#   to = "/"
#   status = 302
#   conditions = {Language = ["de"]}
