# [dev]
#   command = "gatsby develop" # Command to start your dev server
#   port = 8001 # Port that the dev server will be accessible on
#   targetPort = 8000 # Port of target app server
#   publish = "_site" # If you use a _redirect file, provide the path to your static content folder
#   autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address
#   framework = "#custom"


# # Redirect netlify domain to prevent duplicate content on google
# [[redirects]]
#     from = "https://pixelpink.netlify.app/*"
#     to = "https://pixel-pink.de/:splat"
#     status = 301
#     force = true

# # Redirect www 
# [[redirects]]
#     from = "https://www.pixel-pink.de/*"
#     to = "https://pixel-pink.de/:splat"
#     status = 301
#     force = true

# Content got removed permanentely
[[redirects]]
  from = "/more.html"
  to = "/"
  status = 410
  force = false

# Redirect english browsers to english page
[[redirects]]
    from = "/*"
    to = "/en/:splat"
    status = 302
    conditions = {Language = "en"}

# Redirect german browsers to german page
[[redirects]]
    from = "/en/*"
    to = "/:splat"
    status = 302
    conditions = {Language = "de"}
