[[redirects]]
  from = "https://pixelpink.netlify.com/*"
  to ="https://pixel-pink.de/:splat"
  status = 301

[[redirects]]
  from = "https://www.pixel-pink.de/*"
  to ="https://pixel-pink.de/:splat"
  status = 301

[[redirects]]
  from = "/more.html"
  status = 410


# Redirect browsers set to englisch 
[[redirects]]
  from = "/"
  to = "/en/:splat"
  status = 302
  conditions = {Language = ["en"]}

